/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Contact: typeof import('./page/contact/Contact.vue')['default']
    DefaultButton: typeof import('./components/ui/DefaultButton.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Experience: typeof import('./page/experience/Experience.vue')['default']
    Header: typeof import('./components/header/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./page/home/Home.vue')['default']
    MobileNav: typeof import('./components/header/MobileNav.vue')['default']
    Nav: typeof import('./components/header/Nav.vue')['default']
    Photo: typeof import('./page/home/Photo.vue')['default']
    Project: typeof import('./page/project/Project.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectLanguage: typeof import('./components/header/SelectLanguage.vue')['default']
    Service: typeof import('./page/service/Service.vue')['default']
    Skill: typeof import('./page/home/Skill.vue')['default']
    Stats: typeof import('./page/home/Stats.vue')['default']
  }
}
